### ISSUE TITLE
Fix indicator labeling

### ISSUE THREAD

**Issue by MHMCD** [CodeFoxNL/Contextproject-VH#35]
We currently call indicators by their ID, this could be catastrophic when we are adding the agent to another environment, it should be refactored to adding the indicators according to their name which should be identical across environments.

**Comment by lisv** [comment]
In what files does this issue occur exactly? Only in tygronGoals?

**Comment by MHMCD** [comment]
all indicators which have a hardcoded indicatorID should be refactored.
